trigger:
  - master
variables:
  - group: uipath-cicd
  - name: agent.preferPowerShellOnContainers
    value: "True"

stages:
  - stage: Build
    displayName: Create build artifact
    jobs:
      - job: BuildArtifact
        pool:
          vmImage: "windows-latest"
        container:
          image: uipathrobot.azurecr.io/uipathrobot:latest
          endpoint: uipathrobotmp

        steps:
          - script: C:\UiPath\UiRobot.exe pack $(Build.SourcesDirectory)\project.json -o $(Build.ArtifactStagingDirectory)\ -v 1.0.$(Build.BuildNumber)
            displayName: "Build the artifact"
          - publish: $(Build.ArtifactStagingDirectory)
            artifact: drop

  - stage: DeployUat
    displayName: Deploy build artifact to UAT
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: deployUat
        displayName: Deploy package to UAT Orchestrator
        pool:
          vmImage: "windows-latest"
        container:
          image: uipathrobot.azurecr.io/uipathrobot:latest
          endpoint: uipathrobotmp
        environment: uat
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop
                  displayName: Download build artifact on build agent
                - powershell: |
                    Import-Module UiPath.Powershell
                    $token = Get-UiPathAuthToken -ClientId $(uatClientId) -UserKey $(uatUserKey) -AccountName $(uatAccountName) -CloudDeployment 'Production' -TenantName $(uatTenantName)
                    Add-UiPathPackage -PackageFile $(Pipeline.Workspace)\drop\uipath-sample.1.0.$(Build.BuildNumber).nupkg -AuthToken $token

  - stage: DeployProd
    displayName: Deploy build artifact to Prod
    dependsOn: DeployUat
    condition: succeeded()
    jobs:
      - deployment: deployProd
        displayName: Deploy package to Prod Orchestrator
        pool:
          vmImage: "windows-latest"
        container:
          image: uipathrobot.azurecr.io/uipathrobot:latest
          endpoint: uipathrobotmp
        environment: prod
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop
                  displayName: Download build artifact on build agent
                - powershell: |
                    Import-Module UiPath.Powershell
                    $token = Get-UiPathAuthToken -ClientId $(prodClientId) -UserKey $(prodUserKey) -AccountName $(prodAccountName) -CloudDeployment 'Production' -TenantName $(prodTenantName)
                    Add-UiPathPackage -PackageFile $(Pipeline.Workspace)\drop\uipath-sample.1.0.$(Build.BuildNumber).nupkg -AuthToken $token
